name: guap_mobile
description: Mobile version of GUAP application
# Built with Flutter 1.22.6 with "--no-tree-shake-icons" flag
# Flutter 2.0.0+ will NOT work.
# To build for Android, add "key.properties" to android/ folder

version: 1.0.3+9

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: ^1.0.3                      # tuples support
  optional: ^5.0.0                   # options support
  intl: ^0.16.1                      # formatting messages
  http: ^0.12.1                      # http client
  crypto: 2.1.4                      # SHA-256
  shared_preferences: ^0.5.7+3       # key-value storage
  flutter_redux: 0.5.0               # redux
  redux_thunk: ^0.2.1                # redux thunk middleware
  json_annotation: ^3.0.0            # json auto-generation
  flutter_slidable: ^0.5.4           # dismissible list tiles
  flutter_treeview: ^0.4.1+1         # treeview
  flutter_typeahead: ^1.8.3          # auto-complete textbox
  flutter_rounded_date_picker: 1.0.4 # calendar
  rflutter_alert: ^1.0.2             # pop-ups
  firebase_messaging: ^8.0.0-dev.15  # push notifications

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0               # json auto-generation
  json_serializable: ^3.2.0          # json auto-generation

flutter:

  uses-material-design: true
